import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Praesentium
          ipsa maxime, perferendis consequuntur doloribus, nam, ad modi animi
          iste neque inventore quas nemo fuga fugiat iusto! Eum quod aperiam
          velit?
        </p>
      </main>
    </>
  );
};

export default Home;
